### ISSUE TITLE
daemon not installing

### ISSUE THREAD

**Issue by u2716** [john-tornblom/tiny-ps4-shell#2]
ps4 7.5X.

installing and launching telnet shell pkg , i get this error "Unable to install /mnt/sandbox/BREW0009_000/app0/daemon/eboot.bin"

**Comment by john-tornblom** [comment]
Hmmm, interesting, I can't seem to reproduce this on 6.72. You can try transfer the manually via ftp:
From the build root, transfer:
  - daemon.bin ---> /system/vsh/app/BREW00009/eboot.bin
  - daemon.sfo ---> /system/vsh/app/BREW00009/sce_sys/param.sfo

After that, you should be able to launch it from the ps4 homescreen
Let me know if that works.

**Comment by u2716** [comment]
it works, thanks <3
